$(function(){
    $('.alien-textbox').alienTextbox({
    	height:40,
    	width:180,
    	placeholder:'text输入框'
    });
    $('.alien-header').alienHeader({
    	fontSize: 34
    });
    $('#toggle-on').alienToggle();
    $('#toggle-off').alienToggle({
        status:0
    });
    $('.alien-radio').alienRadio({
    	item:[
    		{text:'均匀分布',val:1,chosen:false},
    		{text:'正态分布',val:2,chosen:false},
    		{text:'随机分布',val:3,chosen:true}
    	]
    });
    $('.alien-checkbox').alienCheckbox({
    	item:[
    		{text:'Jason Mraz',val:1,chosen:false},
    		{text:'张国荣',val:2,chosen:true},
    		{text:'谢安琪',val:3,chosen:false},
    		{text:'陈奕迅',val:4,chosen:true}
    	]
    });
    $('.alien-combobox').alienCombobox({
        item:[
            {text:'与我常在',val:1,chosen:false},
            {text:'路过蜻蜓',val:2,chosen:false},
            {text:'当爱已成往事',val:3,chosen:true},
            {text:'陀飞轮',val:4,chosen:false},
            {text:'红',val:5,chosen:false}
        ]
    });
    $('.alien-spinner').alienSpinner({
        min:10,
        max:85,
        increment:8,
        init:12
    });
    $('#slider1').alienSlider({
        min:10,
        max:86,
        step:2,
        init:28
    });
    $('#slider2').alienSlider({
        min:10,
        max:86,
        step:2,
        init:56
    });

    $('.alien-datebox').alienDatebox();
    $('.alien-searchbox').alienSearchbox();
    $('#tooltip-top').alienTooltip({
        position:'top',
        text:'连续按B的话就会出现连续技，各个角色都不相同，如果是连续按A的话那就是不断移动，按住不放就可以连续跳跃，中间可以插投掷；按X键就是投掷了.'
    });
    $('#tooltip-bottom').alienTooltip({
        position:'bottom',
        text:'B键普通攻击，A键跳跃，X键投掷，Y键集气、曝气，RT防御、LT分身，这些招数运用的时机是需要我们不断练习的，LB\RB觉醒后两个技能，十字键一般都是加攻防、减敌攻防、炸弹等其他一些东西，BUFF、DEBUFF都有图标。'
    });
    $('#tooltip-right').alienTooltip({
        position:'right',
        text:'Y键按住就是集气（查克拉），按一下配合B就是小忍术（如果按住B不放可以蓄力，忍术打出去就是中等伤害了）、A就是鬼步了，快速接近\离开对手，X就是投掷(2个)。'
    });
    $('#tooltip-left').alienTooltip({
        position:'left',
        text:'按两下后（比按一下角色身上查克拉要范围大）配合B就是最大伤害的忍术了，X也是投掷（3个），X后会直接攻击，可以接B出连招，当然查克拉消耗也大了。'
    });
});